from .constantes_redes_neuronales import *

__all__ = [
    'TAMAÑO_ENTRADA_DIGITOS',
    'NUMERO_CLASES_DIGITOS', 
    'TASA_APRENDIZAJE_DEFECTO',
    'EPOCAS_MAXIMAS_DEFECTO',
    'ERROR_OBJETIVO_DEFECTO',
    'ARQUITECTURAS_TP2',
    'PATRONES_XOR_ENTRADA',
    'PATRONES_XOR_SALIDA',
    'PATRONES_AND_ENTRADA',
    'PATRONES_AND_SALIDA',
    'PATRONES_OR_ENTRADA',
    'PATRONES_OR_SALIDA'
]
