TAMAÑO_ENTRADA_DIGITOS = 35
NUMERO_CLASES_DIGITOS = 10
TAMAÑO_ENTRADA_XOR = 2
TAMAÑO_SALIDA_XOR = 1

TASA_APRENDIZAJE_DEFECTO = 0.1
EPOCAS_MAXIMAS_DEFECTO = 10000
ERROR_OBJETIVO_DEFECTO = 0.01
INTERVALO_IMPRESION_DEFECTO = 1000

PROBABILIDAD_RUIDO_DEFECTO = 0.02
PORCENTAJE_ENTRENAMIENTO = 0.8
PORCENTAJE_PRUEBA = 0.2

PRECISION_DECIMALES = 4
ANCHO_COLUMNA_MATRIZ = 8

VALOR_ACTIVACION_ALTO = 1
VALOR_ACTIVACION_BAJO = -1
VALOR_ACTIVACION_ALTO_NORMALIZADO = 0.9
VALOR_ACTIVACION_BAJO_NORMALIZADO = 0.1

RANGO_PESO_MINIMO = -0.5
RANGO_PESO_MAXIMO = 0.5

ARQUITECTURAS_TP2 = {
    'MINIMA': [35, 10, 1],
    'COMPACTA': [35, 15, 8, 1],
    'DIRECTA_ORIGINAL': [35, 20, 10, 1],
    'PROFUNDA': [35, 30, 20, 15, 10, 1],
    'BALANCEADA': [35, 25, 12, 1],
    'DOS_ETAPAS': [35, 25, 15, 10],
    'CLASIFICACION_10_CLASES': [35, 20, 15, 10]
}

PATRONES_XOR_ENTRADA = [[-1, 1], [1, -1], [-1, -1], [1, 1]]
PATRONES_XOR_SALIDA = [1, 1, -1, -1]

PATRONES_AND_ENTRADA = [[-1, 1], [1, -1], [-1, -1], [1, 1]]
PATRONES_AND_SALIDA = [-1, -1, -1, 1]

PATRONES_OR_ENTRADA = [[-1, 1], [1, -1], [-1, -1], [1, 1]]
PATRONES_OR_SALIDA = [1, 1, -1, 1]

ARCHIVO_DATOS_DIGITOS = "numeros_decimales.txt"
ARCHIVO_ENTRENAMIENTO_TP1 = "TP1-ej2-Conjunto-entrenamiento.txt"
ARCHIVO_SALIDA_TP1 = "TP1-ej2-Salida-deseada.txt"

MENSAJE_CONVERGENCIA = "¡Convergencia alcanzada!"
MENSAJE_NO_CONVERGENCIA = "No se alcanzó la convergencia en el número máximo de épocas."
MENSAJE_INICIO_ENTRENAMIENTO = "Iniciando entrenamiento..."
MENSAJE_FIN_ENTRENAMIENTO = "Entrenamiento completado."
